In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 619.0 kB/s eta 0:00:00 0:00:01
Requirement already satisfied: numpy>=1.26.0 in /home/shailesh/Desktop/education/DSML-10/.venv/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/shailesh/Desktop/education/DSML-10/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/shailesh/Desktop/education/DSML-10/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 11.0 MB/s eta 0:00:0000:0100:01
Installing collected packages: pandas
Successfully installed pandas-3.0.2

In [ ]:
import pandas as pd
# https://pandas.pydata.org/docs/reference/index.html

In [3]:
pd.__version__

'3.0.2'

## Datatype of Pandas
1. DataFrame : 2D Table with rows and columns
2. Series    : 1D array - like

## Creating DataFrame

In [4]:
data = {
    "name" : [ "bob", "charls", "sweety"],
    "age" : [ 25,45,33]
}

In [5]:
df = pd.DataFrame(data)
df

     name  age
0     bob   25
1  charls   45
2  sweety   33

## Reading Data From Files

- `pd.read_csv(file_path, sep=',')`: Reads CSV (Comma Separated Value) file and returns a Pandas DataFrame
    - *file_path*: Path to csv file
    - *sep*: Symbol separating different columns (default=',')

In [15]:
titanic_df = pd.read_csv("titanic_data.csv", sep = ",", header = 0)

In [16]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

- `pd.read_json(file_path, sep=',')`: Reads Json file and returns a Pandas DataFrame
    - *file_path*: Path to csv file
    - *sep*: Symbol separating different columns (default=',')

In [13]:
employee = pd.read_json("generated.json", orient="records")
employee

,index,guid,isActive,balance,picture,age,eyeColor,name,gender,company,email,phone,address,favoriteFruit
0,0,467da7a5-8b56-4583-adbe-a90dfcabbe6e,True,"$1,724.44",http://placehold.it/32x32,35,brown,Yvette Stokes,female,HARMONEY,yvettestokes@harmoney.com,+1 (867) 447-2472,"170 Thames Street, Worton, Connecticut, 2086",apple
1,1,c44f1910-a338-4297-836a-77bf2b15a94c,False,"$1,189.81",http://placehold.it/32x32,26,green,Hebert Vaughn,male,ZILENCIO,hebertvaughn@zilencio.com,+1 (904) 578-3037,"196 Ide Court, Joppa, Montana, 6339",banana
2,2,9a79bcca-0095-445e-a4fd-a6622bfb9ebe,True,"$2,219.87",http://placehold.it/32x32,28,green,Ora Noel,female,QUAREX,oranoel@quarex.com,+1 (916) 414-3111,"719 Tiffany Place, Trona, Michigan, 6873",strawberry
3,3,28bdbf29-6708-44f9-a645-70a091426a29,False,"$3,250.34",http://placehold.it/32x32,21,blue,Boone Silva,male,KIGGLE,boonesilva@kiggle.com,+1 (980) 433-2030,"163 Rutledge Street, Boling, Vermont, 415",strawberry
4,4,b703fc56-5f05-4f71-9bd9-98ca3d83724e,True,"$2,330.65",http://placehold.it/32x32,30,blue,Noble Green,male,SIGNITY,noblegreen@signity.com,+1 (847) 574-2218,"244 Scott Avenue, Coultervillle, South Dakota,...",banana
5,5,462a051f-38db-4cff-af3a-6912dd4e8f90,False,"$2,985.06",http://placehold.it/32x32,38,brown,Angelica Hardin,female,PLUTORQUE,angelicahardin@plutorque.com,+1 (836) 537-2811,"586 Essex Street, Blodgett, New Jersey, 5545",banana

## Accessing Data

In [17]:
titanic_df.shape

(891, 12)

In [18]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

Titanic dataset has 12 columns and 891 rows.

In [20]:
# Reading a Column

# name = titanic_df["Name"]
name = titanic_df.Name
name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [21]:
type(name)

pandas.Series

In [22]:
name_age = titanic_df[["Name", "Age"]]
name_age

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [25]:
# Reading Rows
name_age.loc[2,"Age"]

np.float64(26.0)

In [27]:
# Reading Rows
name_age.loc[2:10,]

                                                 Name   Age
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0

In [28]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [29]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [34]:
titanic_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [36]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [51]:
## Condition Based Filtering

In [41]:
mask = titanic_df.Survived == 1
total_survived = titanic_df[mask]

In [ ]:
total_survived

np.float64(28.343689655172415)

In [46]:
titanic_df.shape

(891, 12)