In [1]:
import pandas as pd

titanic_df = pd.read_csv("update_titanic_data.csv")

titanic_df.head()

,Survived,initials,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,PStatus
0,0,Mr,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,False,S,3
1,1,Mrs,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,True,C,1
2,1,Miss,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,False,S,3
3,1,Mrs,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,True,S,1
4,0,Mr,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,False,S,3

In [4]:
# apply , map, aggregate

# def get_initials(name:str)-> str:
#     return name.split(",")[-1].split(".")[0].strip()

get_initials = lambda name : name.split(",")[-1].split(".")[0].strip()

titanic_df.Name.apply(get_initials)

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
831     Rev
832    Miss
833    Miss
834      Mr
835      Mr
Name: Name, Length: 836, dtype: str

In [ ]:
get_initials = lambda name : name.split(",")[-1].split(".")[0].strip()

titanic_df.Name.map(get_initials)

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
831     Rev
832    Miss
833    Miss
834      Mr
835      Mr
Name: Name, Length: 836, dtype: str

In [11]:
get_max = lambda values: values.max()

titanic_df.Age.aggregate(["mean","sum", get_max])

mean           28.284689
sum         23646.000000
<lambda>       55.000000
Name: Age, dtype: float64

### Handling Incorrect Data

In [14]:
import numpy as np

data = pd.DataFrame({
    "id":[1,3,5,7,9],
    "name":["John","Jane","Jennifer","Johan","Jeff"],
    "age":[25,-32,19,42,"55"],
    "gender" : ["M","M","Z","F","F"],
    "income":[400, 700, 300, np.nan, 600]
})

In [15]:
data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane  -32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [16]:
data.dtypes

id          int64
name          str
age        object
gender        str
income    float64
dtype: object

In [17]:
data = data.astype({"age":"int16"})
data.age = abs(data.age)

In [18]:
data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane   32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [22]:
data[data.gender.isin(["M","F"])]

   id   name  age gender  income
0   1   John   25      M   400.0
1   3   Jane   32      M   700.0
3   7  Johan   42      F     NaN
4   9   Jeff   55      F   600.0

In [23]:
titanic_df

,Survived,initials,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,PStatus
0,0,Mr,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,False,S,3
1,1,Mrs,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,True,C,1
2,1,Miss,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,False,S,3
3,1,Mrs,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,True,S,1
4,0,Mr,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,False,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...
831,0,Mr,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,13.0000,False,S,2
832,1,Miss,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.0000,True,S,1
833,0,Miss,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.5,1.0,2.0,W./C. 6607,23.4500,False,S,3
834,1,Mr,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,True,C,1
835,0,Mr,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.7500,False,Q,3